#! /usr/bin/env python3
import sys

import rospy

from waypoint_dispatching.waypoint_client import waypoint_client

if __name__ == "__main__":

    try:
        rospy.init_node("waypoint_client")
        result = waypoint_client()
        # print("Result:", ", ".join([str(n) for n in result.sequence]))
    except rospy.ROSInterruptException:
        print("program interrupted before completion", file=sys.stderr)
